branch-defaults:
  aws:
    environment: pharcoder-dev
  dev:
    environment: pharcoder-dev
  master:
    environment: pharcoder-single-1
deploy:
  artifact: deployments/web.zip
global:
  application_name: pharcoder-dev
  default_ec2_keyname: eb-cli
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
