branch-defaults:
  aws:
    environment: pharcoder-single-1
  master:
    environment: pharcoder-single-1
global:
  application_name: pharcoder-dev
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
deploy:
  artifact: deployments/web.zip