branch-defaults:
  aws:
    environment: pharcoder-dev
  master:
    environment: pharcoder-dev
global:
  application_name: pharcoder
  default_ec2_keyname: jason-personal
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
