branch-defaults:
  dev:
    environment: Starcoder202111-env
environment-defaults:
  Starcoder2021-env:
    branch: null
    repository: null
  Starcoder202111-env:
    branch: null
    repository: null
global:
  application_name: starcoder2021-11
  default_ec2_keyname: starcoder2021-11
  default_platform: Node.js 10
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
