branch-defaults:
  aws:
    environment: pharcoder-dev
  dev:
    environment: pharcoder-dev
  jdm:
    environment: pharcoder-game-portals
  master:
    environment: pharcoder-single-1
deploy:
  artifact: deployments/web.zip
global:
  application_name: pharcoder-dev
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: git
